/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    announcements: Announcement;
    bulletins: Bulletin;
    sermons: Sermon;
    posts: Post;
    newcomers: Newcomer;
    media: Media;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    bulletins: BulletinsSelect<false> | BulletinsSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    newcomers: NewcomersSelect<false> | NewcomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'special-banner': SpecialBanner;
    'offering-page': OfferingPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'special-banner': SpecialBannerSelect<false> | SpecialBannerSelect<true>;
    'offering-page': OfferingPageSelect<false> | OfferingPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * 기본 페이지와 콘텐츠 게시판은 위 목록의 관리 위치에서 수정하고, 여기는 별도로 필요한 독립 페이지를 만듭니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'pageBanner';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('internal' | 'reference' | 'custom') | null;
            newTab?: boolean | null;
            /**
             * 고정 페이지의 본문은 메뉴 화면이 아니라 해당 CMS 영역에서 관리합니다. 예배 안내는 홈/디자인/교회 정보, 최신 설교는 설교, 공지사항은 공지사항에서 수정합니다.
             */
            internalPath?:
              | ('/' | '/about' | '/worship' | '/sermon' | '/announcements' | '/bulletins' | '/newcomer' | '/offering')
              | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  /**
   * 기본 문단은 미리 추가되어 있습니다. 사진, 유튜브, 일정이 필요할 때만 섹션을 추가하세요.
   */
  layout?:
    | (
        | ContentBlock
        | MediaBlock
        | {
            /**
             * YouTube URL에서 v= 뒤의 값 (예: dQw4w9WgXcQ)
             */
            videoId: string;
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'youtubeBlock';
          }
        | {
            /**
             * 인스타그램 게시물에서 공유 > 임베드로 복사한 코드를 붙여넣으세요
             */
            embedCode: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instagramBlock';
          }
        | {
            title?: string | null;
            items?:
              | {
                  dayTime: string;
                  name: string;
                  location?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'scheduleBlock';
          }
        | {
            driveLink: string;
            title?: string | null;
            showPreview?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'googleDriveBlock';
          }
        | OfferingBlock
        | {
            limit?: number | null;
            showPinnedFirst?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'announcementsBlock';
          }
        | {
            title?: string | null;
            description?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bulletinsBlock';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * 자동으로 채워집니다. 예약/수정이 필요할 때만 바꾸세요.
   */
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * 제목을 기준으로 자동 생성됩니다. 필요하면 직접 수정할 수 있습니다.
   */
  slug?: string | null;
  /**
   * 비워두면 최상위 페이지로 생성됩니다. 하위 페이지로 만들 때만 선택하세요.
   */
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 글 제목과 본문만 입력하면 URL과 작성자 정보는 자동으로 관리됩니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * 구글드라이브 파일 링크를 입력하면 미리보기가 표시됩니다
   */
  googleDriveLink?: string | null;
  /**
   * 자동으로 채워집니다. 예약/수정이 필요할 때만 바꾸세요.
   */
  publishedAt?: string | null;
  /**
   * 기본값을 그대로 두고, 필요할 때만 작성자를 지정하세요.
   */
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * 제목을 기준으로 자동 생성됩니다. 필요하면 직접 수정할 수 있습니다.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 사이트에서 사용하는 이미지, 주보 파일, QR 코드 등을 보관합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * CMS에 로그인할 수 있는 관리자 계정을 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('internal' | 'reference' | 'custom') | null;
          newTab?: boolean | null;
          /**
           * 고정 페이지의 본문은 메뉴 화면이 아니라 해당 CMS 영역에서 관리합니다. 예배 안내는 홈/디자인/교회 정보, 최신 설교는 설교, 공지사항은 공지사항에서 수정합니다.
           */
          internalPath?:
            | ('/' | '/about' | '/worship' | '/sermon' | '/announcements' | '/bulletins' | '/newcomer' | '/offering')
            | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferingBlock".
 */
export interface OfferingBlock {
  title?: string | null;
  /**
   * 헌금 관련 안내 문구 (선택 사항)
   */
  description?: string | null;
  /**
   * SiteSettings의 헌금 계좌 정보를 표시합니다
   */
  showBankInfo?: boolean | null;
  /**
   * SiteSettings의 카카오페이 QR 코드를 표시합니다 (등록된 경우)
   */
  showKakaoPay?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'offeringBlock';
}
/**
 * 공지 글을 작성하면 /announcements 게시판과 홈 공지 섹션에 자동으로 노출됩니다. 별도 페이지를 만들 필요가 없습니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 비워두면 지금 시각으로 저장됩니다.
   */
  publishedAt: string;
  isPinned?: boolean | null;
  /**
   * 구글드라이브 파일 링크를 입력하면 미리보기가 표시됩니다
   */
  googleDriveLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 주보 파일만 올려도 날짜와 제목은 자동으로 채워집니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulletins".
 */
export interface Bulletin {
  id: number;
  /**
   * 비워두면 주보 날짜 기준으로 자동 생성됩니다.
   */
  title?: string | null;
  date: string;
  /**
   * 체크하면 로그인 없이도 열람 가능합니다.
   */
  isPublic?: boolean | null;
  /**
   * PDF 또는 이미지 파일을 업로드하세요.
   */
  file?: (number | null) | Media;
  /**
   * 이번 주 설교 제목이나 특별 사항을 입력하세요.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 설교 제목과 YouTube URL만 입력해도 영상 정보와 공개 상태가 자동으로 정리됩니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  /**
   * Enter the sermon title
   */
  title: string;
  /**
   * 제목을 기준으로 자동 생성됩니다. 필요하면 직접 수정할 수 있습니다.
   */
  slug?: string | null;
  /**
   * YouTube video URL
   */
  youtubeUrl: string;
  /**
   * Name of the preacher
   */
  preacher?: string | null;
  /**
   * Scripture reference (e.g., John 3:16, Genesis 1:1-5)
   */
  scriptureRef?: string | null;
  /**
   * Date when the sermon was preached
   */
  sermonDate: string;
  /**
   * Auto-extracted from YouTube URL
   */
  youtubeId?: string | null;
  /**
   * Auto-generated from YouTube ID
   */
  thumbnail?: string | null;
  /**
   * Brief description or summary of the sermon
   */
  description?: string | null;
  /**
   * Sermon series name
   */
  sermonSeries?: string | null;
  /**
   * Select the publication status
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * 새가족 신청과 후속 연락 상태를 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newcomers".
 */
export interface Newcomer {
  id: number;
  name: string;
  /**
   * 예: 010-1234-5678
   */
  phone: string;
  /**
   * 선택 사항
   */
  email?: string | null;
  /**
   * 주일 예배 또는 금요 예배일을 선택해 주세요
   */
  visitDate: string;
  source: 'referral' | 'search' | 'sns' | 'youtube' | 'passingBy' | 'other';
  /**
   * 예: 친구 이름, 검색 키워드, SNS 계정 등 (선택 사항)
   */
  sourceDetail?: string | null;
  /**
   * 여러 개 선택 가능 (선택 사항)
   */
  interests?: ('youngAdults' | 'worship' | 'bibleStudy' | 'service' | 'prayer' | 'smallGroup' | 'notSure')[] | null;
  /**
   * 궁금한 점이나 기도 요청이 있으시면 자유롭게 작성해 주세요 (선택 사항)
   */
  message?: string | null;
  /**
   * 입력하신 정보는 새가족 환영 및 교회 안내 목적으로만 사용되며, 본인의 동의 없이 제3자에게 제공되지 않습니다.
   */
  privacyConsent: boolean;
  /**
   * 관리자만 수정 가능
   */
  status?: ('pending' | 'contacted' | 'visited' | 'registered') | null;
  /**
   * 내부 기록용 (새가족에게 노출되지 않음)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 페이지 URL 변경 시 필요한 고급 리다이렉트 설정입니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * 문의 폼 구성이 필요할 때만 사용하는 고급 설정입니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 폼으로 접수된 응답 목록입니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 검색 인덱스 동기화 결과입니다. 일반 콘텐츠 수정은 소식 글에서 진행합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'bulletins';
        value: number | Bulletin;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'newcomers';
        value: number | Newcomer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    internalPath?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        youtubeBlock?:
          | T
          | {
              videoId?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
        instagramBlock?:
          | T
          | {
              embedCode?: T;
              id?: T;
              blockName?: T;
            };
        scheduleBlock?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    dayTime?: T;
                    name?: T;
                    location?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        googleDriveBlock?:
          | T
          | {
              driveLink?: T;
              title?: T;
              showPreview?: T;
              id?: T;
              blockName?: T;
            };
        offeringBlock?: T | OfferingBlockSelect<T>;
        announcementsBlock?:
          | T
          | {
              limit?: T;
              showPinnedFirst?: T;
              id?: T;
              blockName?: T;
            };
        bulletinsBlock?:
          | T
          | {
              title?: T;
              description?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              internalPath?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferingBlock_select".
 */
export interface OfferingBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  showBankInfo?: T;
  showKakaoPay?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  publishedAt?: T;
  isPinned?: T;
  googleDriveLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulletins_select".
 */
export interface BulletinsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  isPublic?: T;
  file?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  youtubeUrl?: T;
  preacher?: T;
  scriptureRef?: T;
  sermonDate?: T;
  youtubeId?: T;
  thumbnail?: T;
  description?: T;
  sermonSeries?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  googleDriveLink?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newcomers_select".
 */
export interface NewcomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  visitDate?: T;
  source?: T;
  sourceDetail?: T;
  interests?: T;
  message?: T;
  privacyConsent?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * 홈 메인 화면을 섹션 단위로 편집하고, 교회 정보/예배/디자인/SNS 설정을 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * 홈페이지 상단 배경 이미지. 권장 해상도: 1920x1080 이상
   */
  heroImage?: (number | null) | Media;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroPrimaryLabel?: string | null;
  heroPrimaryUrl?: string | null;
  heroSecondaryLabel?: string | null;
  heroSecondaryUrl?: string | null;
  /**
   * 각 섹션 카드 안에서 홈에 보이는 형태를 보면서 바로 수정합니다. 행 추가/삭제로 섹션을 추가하거나 제거하고, 드래그로 순서를 바꿉니다.
   */
  homeSections?:
    | {
        enabled?: boolean | null;
        /**
         * 섹션 역할은 어떤 콘텐츠를 가져올지 결정합니다. 예: 공지사항 섹션은 공지사항 게시글을 가져옵니다.
         */
        sectionType: 'intro' | 'announcements' | 'sermons' | 'instagram' | 'map';
        /**
         * 예: ABOUT US, NOTICE, SERMON처럼 제목 위에 작게 표시됩니다.
         */
        eyebrow?: string | null;
        title?: string | null;
        /**
         * 홈 화면에 표시되는 설명 문구입니다. 비워두면 해당 섹션의 기본 구성만 표시합니다.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  churchName: string;
  englishName?: string | null;
  tagline?: string | null;
  subTagline?: string | null;
  /**
   * Header와 히어로에 사용할 로고입니다. 비워두면 기본 로고 파일을 사용합니다.
   */
  logo?: (number | null) | Media;
  /**
   * GNB에 표시되는 로고 높이(px)입니다. 기본값은 40입니다.
   */
  headerLogoHeight?: number | null;
  /**
   * 어두운 상단 배경에서 흰색 로고처럼 보여야 하면 켜두세요. 원본 색상을 그대로 쓰려면 끕니다.
   */
  headerLogoInvert?: boolean | null;
  denomination?: string | null;
  churchDescription?: string | null;
  churchVision?: string | null;
  churchQuote?: string | null;
  coreValues?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  pastorName?: string | null;
  pastorTitle?: string | null;
  pastorPhoto?: (number | null) | Media;
  pastorBio?: string | null;
  pastorQuote?: string | null;
  visitorNotes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  worshipServices?:
    | {
        name: string;
        time: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  worshipOrder?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  address?: string | null;
  addressDetail?: string | null;
  transitInfo?: string | null;
  parkingInfo?: string | null;
  mapLat?: number | null;
  mapLng?: number | null;
  /**
   * 색상 칸을 눌러 컬러피커로 선택하거나 HEX 값을 직접 입력할 수 있습니다.
   */
  design?: {
    primaryColor?: string | null;
    primaryLightColor?: string | null;
    secondaryColor?: string | null;
    backgroundColor?: string | null;
    sectionBackgroundColor?: string | null;
    darkSectionBackgroundColor?: string | null;
    cardBackgroundColor?: string | null;
    textColor?: string | null;
    mutedTextColor?: string | null;
    borderColor?: string | null;
    headerBackgroundColor?: string | null;
    footerBackgroundColor?: string | null;
    heroOverlayColor?: string | null;
    /**
     * 0은 투명, 100은 완전 불투명입니다.
     */
    heroOverlayOpacity?: number | null;
    showHeroPattern?: boolean | null;
    heroTitleFontSize?: number | null;
    heroSubtitleFontSize?: number | null;
    sectionTitleFontSize?: number | null;
    bodyFontSize?: number | null;
    /**
     * 은은한 텍스처나 패턴용입니다. 비워두면 배경 컬러만 사용합니다.
     */
    pageBackgroundImage?: (number | null) | Media;
    /**
     * Instagram 같은 어두운 섹션에 사용할 배경 이미지입니다.
     */
    darkSectionBackgroundImage?: (number | null) | Media;
  };
  youtubeChannelUrl?: string | null;
  /**
   * 비워도 채널 URL에서 자동 해석을 시도합니다. UC로 시작하는 채널 ID를 넣으면 더 안정적입니다.
   */
  youtubeChannelId?: string | null;
  youtubeVideoCount?: number | null;
  instagramUrl?: string | null;
  instagramHandle?: string | null;
  /**
   * Instagram API 제약 때문에 안정 운영은 게시물 ID를 관리자가 등록하는 방식으로 시작합니다.
   */
  instagramPosts?:
    | {
        type: 'p' | 'reel';
        /**
         * 예: https://www.instagram.com/p/POST_ID/ 에서 POST_ID 부분
         */
        postId: string;
        /**
         * 홈 화면 Instagram 카드에 표시할 이미지입니다. 비워두면 기본 카드 디자인으로 표시됩니다.
         */
        thumbnail?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  offeringBankName?: string | null;
  offeringAccountNumber?: string | null;
  offeringAccountHolder?: string | null;
  offeringKakaoPayQr?: (number | null) | Media;
  offeringNotes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 사이트 상단 내비게이션 메뉴를 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * 상단에 보일 링크의 이름과 순서를 관리합니다. 링크 대상 페이지의 본문은 각 관리 화면에서 수정합니다. 예배 안내는 홈페이지 빌더의 예배/오시는 길, 최신 설교는 설교, 공지사항은 공지사항, 주보는 주보, 헌금 안내는 헌금 안내 페이지에서 관리합니다.
   */
  navItems?:
    | {
        link: {
          type?: ('internal' | 'reference' | 'custom') | null;
          newTab?: boolean | null;
          /**
           * 고정 페이지의 본문은 메뉴 화면이 아니라 해당 CMS 영역에서 관리합니다. 예배 안내는 홈/디자인/교회 정보, 최신 설교는 설교, 공지사항은 공지사항에서 수정합니다.
           */
          internalPath?:
            | ('/' | '/about' | '/worship' | '/sermon' | '/announcements' | '/bulletins' | '/newcomer' | '/offering')
            | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 사이트 하단 링크, 예배 시간, 주소, 연락처를 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('internal' | 'reference' | 'custom') | null;
          newTab?: boolean | null;
          /**
           * 고정 페이지의 본문은 메뉴 화면이 아니라 해당 CMS 영역에서 관리합니다. 예배 안내는 홈/디자인/교회 정보, 최신 설교는 설교, 공지사항은 공지사항에서 수정합니다.
           */
          internalPath?:
            | ('/' | '/about' | '/worship' | '/sermon' | '/announcements' | '/bulletins' | '/newcomer' | '/offering')
            | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  worshipSchedule?: string | null;
  address?: string | null;
  churchPhone?: string | null;
  legalText?: string | null;
  showThemeSelector?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 기간을 지정해 사이트 상단에 노출할 임시 안내 배너를 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-banner".
 */
export interface SpecialBanner {
  id: number;
  /**
   * 체크하면 배너가 표시됩니다
   */
  enabled?: boolean | null;
  /**
   * 배너에 표시될 주요 문구 (예: 🌟 부활절 특별예배)
   */
  text: string;
  /**
   * 추가 안내 문구 (예: 4월 5일 (토) 오전 10:30)
   */
  subtext?: string | null;
  /**
   * 색상 칸을 눌러 선택하거나 HEX 값을 직접 입력하세요.
   */
  backgroundColor?: string | null;
  /**
   * 색상 칸을 눌러 선택하거나 HEX 값을 직접 입력하세요.
   */
  textColor?: string | null;
  /**
   * 배너 표시 시작일 (비워두면 즉시 표시)
   */
  startDate?: string | null;
  /**
   * 배너 표시 종료일 (이 날짜가 지나면 자동으로 숨겨집니다)
   */
  endDate: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 헌금 안내 페이지의 문구, 계좌, 안내 사항을 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offering-page".
 */
export interface OfferingPage {
  id: number;
  /**
   * 헌금 안내 페이지 상단에 표시되는 소개 문구
   */
  introText?: string | null;
  bankAccounts?:
    | {
        bankName: string;
        accountNumber: string;
        accountHolder: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 헌금 관련 안내 사항 (줄바꿈으로 항목 구분)
   */
  notes?: string | null;
  bibleVerse?: string | null;
  bibleReference?: string | null;
  offeringTypes?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroImage?: T;
  heroEyebrow?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroPrimaryLabel?: T;
  heroPrimaryUrl?: T;
  heroSecondaryLabel?: T;
  heroSecondaryUrl?: T;
  homeSections?:
    | T
    | {
        enabled?: T;
        sectionType?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  churchName?: T;
  englishName?: T;
  tagline?: T;
  subTagline?: T;
  logo?: T;
  headerLogoHeight?: T;
  headerLogoInvert?: T;
  denomination?: T;
  churchDescription?: T;
  churchVision?: T;
  churchQuote?: T;
  coreValues?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  pastorName?: T;
  pastorTitle?: T;
  pastorPhoto?: T;
  pastorBio?: T;
  pastorQuote?: T;
  visitorNotes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  worshipServices?:
    | T
    | {
        name?: T;
        time?: T;
        description?: T;
        id?: T;
      };
  worshipOrder?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  address?: T;
  addressDetail?: T;
  transitInfo?: T;
  parkingInfo?: T;
  mapLat?: T;
  mapLng?: T;
  design?:
    | T
    | {
        primaryColor?: T;
        primaryLightColor?: T;
        secondaryColor?: T;
        backgroundColor?: T;
        sectionBackgroundColor?: T;
        darkSectionBackgroundColor?: T;
        cardBackgroundColor?: T;
        textColor?: T;
        mutedTextColor?: T;
        borderColor?: T;
        headerBackgroundColor?: T;
        footerBackgroundColor?: T;
        heroOverlayColor?: T;
        heroOverlayOpacity?: T;
        showHeroPattern?: T;
        heroTitleFontSize?: T;
        heroSubtitleFontSize?: T;
        sectionTitleFontSize?: T;
        bodyFontSize?: T;
        pageBackgroundImage?: T;
        darkSectionBackgroundImage?: T;
      };
  youtubeChannelUrl?: T;
  youtubeChannelId?: T;
  youtubeVideoCount?: T;
  instagramUrl?: T;
  instagramHandle?: T;
  instagramPosts?:
    | T
    | {
        type?: T;
        postId?: T;
        thumbnail?: T;
        id?: T;
      };
  offeringBankName?: T;
  offeringAccountNumber?: T;
  offeringAccountHolder?: T;
  offeringKakaoPayQr?: T;
  offeringNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              internalPath?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              internalPath?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  worshipSchedule?: T;
  address?: T;
  churchPhone?: T;
  legalText?: T;
  showThemeSelector?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-banner_select".
 */
export interface SpecialBannerSelect<T extends boolean = true> {
  enabled?: T;
  text?: T;
  subtext?: T;
  backgroundColor?: T;
  textColor?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offering-page_select".
 */
export interface OfferingPageSelect<T extends boolean = true> {
  introText?: T;
  bankAccounts?:
    | T
    | {
        bankName?: T;
        accountNumber?: T;
        accountHolder?: T;
        id?: T;
      };
  notes?: T;
  bibleVerse?: T;
  bibleReference?: T;
  offeringTypes?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}